import type { Child, Evolution, Notification, Session, User } from '../types';

export const MOCK_DATA = {
  user: {
    id: 'u1',
    name: 'Ricardo Silva',
    email: 'ricardo@example.com',
    phone: '(11) 98765-4321',
    avatarUrl: 'https://i.pravatar.cc/150?u=u1',
  } as User,
  children: [
    {
      id: 'c1',
      name: 'Lucas Silva',
      age: 6,
      diagnosis: 'TEA Nível 1',
      parentId: 'u1',
      avatarUrl: 'https://i.pravatar.cc/150?u=c1',
      nextSession: {
        id: 's1',
        childId: 'c1',
        professionalId: 'p1',
        professionalName: 'Dra. Ana Beatriz',
        date: '2026-07-15',
        time: '14:00',
        type: 'Terapia Ocupacional',
        status: 'scheduled',
      },
    },
    {
      id: 'c2',
      name: 'Maya Silva',
      age: 4,
      diagnosis: 'TDP',
      parentId: 'u1',
      avatarUrl: 'https://i.pravatar.cc/150?u=c2',
      nextSession: {
        id: 's2',
        childId: 'c2',
        professionalId: 'p2',
        professionalName: 'Dr. Marcos Lima',
        date: '2026-07-16',
        time: '10:00',
        type: 'Fonoaudiologia',
        status: 'scheduled',
      },
    },
  ] as Child[],
  evolutions: [
    {
      id: 'e1',
      childId: 'c1',
      professionalId: 'p1',
      professionalName: 'Dra. Ana Beatriz',
      date: '2026-07-10',
      description: 'Lucas apresentou excelente evolução na coordenação motora fina, conseguindo realizar o encaixe de peças menores com maior autonomia.',
      attachments: ['relatorio_julho.pdf'],
      photos: ['https://picsum.photos/200/300'],
    },
    {
      id: 'e2',
      childId: 'c1',
      professionalId: 'p1',
      professionalName: 'Dra. Ana Beatriz',
      date: '2026-07-03',
      description: 'Início do trabalho com estímulos sensoriais. Lucas demonstrou resistência inicial, mas adaptou-se bem ao final da sessão.',
      attachments: [],
      photos: [],
    },
  ] as Evolution[],
  sessions: [
    {
      id: 's1',
      childId: 'c1',
      professionalId: 'p1',
      professionalName: 'Dra. Ana Beatriz',
      date: '2026-07-15',
      time: '14:00',
      type: 'Terapia Ocupacional',
      status: 'scheduled',
    },
    {
      id: 's3',
      childId: 'c1',
      professionalId: 'p1',
      professionalName: 'Dra. Ana Beatriz',
      date: '2026-07-01',
      time: '14:00',
      type: 'Terapia Ocupacional',
      status: 'completed',
    },
  ] as Session[],
  notifications: [
    {
      id: 'n1',
      title: 'Nova evolução registrada',
      message: 'Dra. Ana Beatriz registrou uma nova evolução de Lucas sobre a sessão de Terapia Ocupacional.',
      time: 'Há 2 horas',
      read: false,
      type: 'info',
    },
    {
      id: 'n2',
      title: 'Sessão confirmada',
      message: 'A sessão de Fonoaudiologia de Maya para 16/07 foi confirmada pelo Dr. Marcos Lima.',
      time: 'Há 5 horas',
      read: false,
      type: 'success',
    },
    {
      id: 'n3',
      title: 'Lembrete de sessão',
      message: 'Amanhã Lucas tem sessão de Terapia Ocupacional às 14:00 com Dra. Ana Beatriz.',
      time: 'Ontem',
      read: true,
      type: 'warning',
    },
    {
      id: 'n4',
      title: 'Relatório disponível',
      message: 'O relatório mensal de julho de Lucas está disponível para visualização.',
      time: '10/07/2026',
      read: true,
      type: 'info',
    },
    {
      id: 'n5',
      title: 'Pagamento confirmado',
      message: 'O pagamento da sessão de 01/07 de Lucas foi confirmado com sucesso.',
      time: '02/07/2026',
      read: true,
      type: 'success',
    },
  ] as Notification[],
};
